--liquibase formatted sql

--changeset ivanov:1
CREATE TABLE notification_tasks
(
    id                     BIGINT generated by default as identity primary key,
    message                TEXT,
    chat_id                BIGINT    NOT NULL,
    notification_date_time TIMESTAMP NOT NULL
);
